THEANO_FLAGS='device=gpu1' python3 -mnnet.run.srl.run \
--test conll2009.dev \
--data_partition dev \
--test-only \
--test-model conll2009_rm0_pl_a.25_sskip_h512_d.0_l3_gcn_1_gc_drop_.2/best.bin \
--batch 100 \
--freq-voc freq.voc_unk.conll2009 \
--word-voc words.voc_unk.conll2009 \
--p-word-voc p.words.voc_sskip.conll2009 \
--role-voc labels.voc.conll2009 \
--frame-voc frames.voc.conll2009 \
--pos-voc pos.voc.conll2009 \
--word-embeddings word_embeddings_proper.sskip.conll2009.txt \
--dbg-print-rate 200 \
--backoff-threshold 30 \
--rate 0.01 \
--optimizer adam \
--eval-dir ./data/ \
--soft-warnings \
--epochs 20 \
--hps "{'rm':0}"